### ISSUE TITLE
[NEW] 인증 이메일 템플릿 디자인 요청

### ISSUE THREAD

**Issue by Choi-Jiwon-38** [TEAM-LINRING/.github#2]
### Description

`allauth` 패키지를 이용한 인증 이메일에는 템플릿을 적용할 수 있습니다.

|기본 템플릿|현재 템플릿(임시 적용)|
|----------|--------------------|
|![스크린샷 2023-08-30 01 48 22](https://github.com/TEAM-LINRING/.github/assets/81795729/f02c36e8-ced1-49e9-ae6d-6f1db5903a89)|![스크린샷 2023-08-30 01 48 05](https://github.com/TEAM-LINRING/.github/assets/81795729/60368a64-95cb-4a82-b1a3-eaedd4117116)|

기본 템플릿을 그대로 사용하거나 임시로 적용한 템플릿보다는 LINRING의 자체 인증 이메일 템플릿이 있으면 좋을 거 같습니다.
HTML, CSS를 이용하여 템플릿을 작성하기 때문에, 기존 웹 디자인과 같은 방식으로 진행해주시면 될 거 같습니다.

**Comment by jangsumi** [comment]
인증 이메일 디자인 완료했습니다.

1. 타이포 로고는 svg로 export해서 넣어주세요. (추후 로고 디자인 변경될 수 있음)
2. 메일 텍스트는 구글에서 정해둔 폰트만 적용 가능하여 기본 폰트인 Arial 사용했습니다.

위치 : Figma - 알파 프로젝트 LINRING UXUI 디자인 - 확정 디자인

**Comment by Choi-Jiwon-38** [comment]
디자인 확인하였습니다. 고생하셨습니다!
해당 이슈는 완료 되었으므로 close 하겠습니다 :)
